trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '18.x'
#   displayName: 'Install Node.js'

- script: |
    docker-compose -f docker/service.yml build
    docker image tag ${CONTAINER_APP_NAME) $(CONTAINER_REGISTRY)/$(CONTAINER_APP_NAME)
    docker push $(CONTAINER_REGISTRY)/$(CONTAINER_APP_NAME)
  displayName: 'Create Docker image and push to container registry'

- task: AzureWebAppContainer@1
  displayName: 'Azure Web App on Container Deploy: $(CONTAINER_APP_NAME)'
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(webAppName)
    containers: $(CONTAINER_REGISTRY)/$(CONTAINER_APP_NAME)