process.env.OS_KEY = 'testKey'
process.env.OS_SECRET = 'testSecret'
process.env.SERVICE_BUS_CONNECTION_STRING = 'testConnectionString'
process.env.SERVICE_BUS_QUEUE_NAME = 'testQueueName'
process.env.REGISTER_START_ROUTES = 'true'
process.env.CAPTCHA_ENABLED = 'true'
process.env.CAPTCHA_API_KEY = '1234'
process.env.CAPTCHA_SITE_KEY = 'abcd'
