process.env.OS_KEY = 'testKey'
process.env.OS_SECRET = 'testSecret'
process.env.SERVICE_BUS_CONNECTION_STRING = 'testConnectionString'
process.env.SERVICE_BUS_QUEUE_NAME = 'testQueueName'
process.env.AUTH_ACCOUNTS = '[{"id":1,"password":"WPINTERNAL"},{"id":2,"password":"ODINTERNAL"},{"id":3,"password":"RPSMINTERNAL"},{"id":4,"password":"IFINTERNAL"}]'
