import accessibleAutocomplete from 'accessible-autocomplete'
import { panToOSValue, panToPoint, panToBbox } from './map.js'

let autoCompleteValue
const locationSearchButton = document.getElementById('search-location')
const currentLocationErrorId = 'current-location-error'

// Handle desktop search button click
locationSearchButton.addEventListener('click', async (e) => {
  e.preventDefault()
  await handleSearchButtonClick()
})

// Decide what kind of search to run (autocomplete vs manual)
const handleSearchButtonClick = async () => {
  const inputValue = document.getElementById('location').value

  // No input
  if (!inputValue) {
    return setTimeout(() => showError('Enter a search term, for example a nearby town, city or postcode'), 50)
  }

  // Autocomplete selection - pan directly
  if (autoCompleteValue) {
    return panToOSValue(autoCompleteValue)
  }

  // Manual input - run full search
  return searchLocation()
}

const getSearchInputValue = () => {
  // visible input generated by accessible-autocomplete
  const aaInput = document.querySelector('.autocomplete__input')
  if (aaInput && aaInput.value !== undefined) {
    return aaInput.value.trim()
  }

  // fallback
  const originalInput = document.getElementById('location')
  return originalInput?.value?.trim() || ''
}

// Search for a location based on manual input
const searchLocation = async () => {
  const locationString = getSearchInputValue()
  if (locationString.length === 0) {
    return setTimeout(() => showError('Enter a search term, for example a nearby town, city or postcode'), 50)
  }

  const response = await fetch(`/api/location?location=${locationString}`)
  const data = await response.json()

  // Pan map to bounding box if available, otherwise to point
  if (data?.GAZETTEER_ENTRY) {
    hideError()
    if (data.GAZETTEER_ENTRY.MBR_XMIN) {
      return panToBbox([data.GAZETTEER_ENTRY.MBR_XMIN, data.GAZETTEER_ENTRY.MBR_YMIN, data.GAZETTEER_ENTRY.MBR_XMAX, data.GAZETTEER_ENTRY.MBR_YMAX])
    } else {
      return panToPoint([data.GAZETTEER_ENTRY.GEOMETRY_X, data.GAZETTEER_ENTRY.GEOMETRY_Y])
    }
  } else {
    return showError('Enter a different search term, for example a nearby town, city or postcode')
  }
}

// Show GOV.UK error summary + inline error message
const showError = (message) => {
  const currentLocation = document.getElementById('current-location')

  // Remove old point error if exists
  document.getElementById('point-error')?.remove()

  // Remove error state from form group
  const formGroup = document.querySelector('.govuk-form-group')
  formGroup.classList.remove('govuk-form-group--error')

  // Desktop summary
  let desktopSummary = document.querySelector('.govuk-error-summary.map-desktop-only')
  if (!desktopSummary) {
    const formElement = document.querySelector('form')
    formElement.insertAdjacentHTML('beforebegin', `
      <div class="govuk-error-summary map-desktop-only" data-module="govuk-error-summary">
        <div role="alert">
          <h2 class="govuk-error-summary__title">There is a problem</h2>
          <div class="govuk-error-summary__body">
            <ul class="govuk-list govuk-error-summary__list">
              <li><a href="#location" class="error-message">${message}</a></li>
            </ul>
          </div>
        </div>
      </div>
    `)
    desktopSummary = document.querySelector('.govuk-error-summary.map-desktop-only')
  } else {
    desktopSummary.querySelector('.error-message').innerText = message
  }

  // Mobile summary
  const labelWrapper = document.querySelector('.govuk-label-wrapper')
  let mobileSummary = document.querySelector('.govuk-error-summary.map-mobile-only')
  if (!mobileSummary) {
    labelWrapper.insertAdjacentHTML('beforebegin', `
      <div class="govuk-error-summary map-mobile-only" data-module="govuk-error-summary">
        <div role="alert">
          <h2 class="govuk-error-summary__title">There is a problem</h2>
          <div class="govuk-error-summary__body">
            <ul class="govuk-list govuk-error-summary__list">
              <li><a href="#location" class="error-message">${message}</a></li>
            </ul>
          </div>
        </div>
      </div>
    `)
    mobileSummary = document.querySelector('.govuk-error-summary.map-mobile-only')
  } else {
    mobileSummary.querySelector('.error-message').innerText = message
  }

  // Hide H1 label on mobile
  labelWrapper.classList.add('hide-mobile')

  // Insert inline field-level error
  const existingInlineError = document.getElementById(currentLocationErrorId)
  if (!existingInlineError) {
    currentLocation.insertAdjacentHTML('beforebegin', `
      <p class="govuk-error-message" id="${currentLocationErrorId}">
        <span class="govuk-visually-hidden">Error:</span> ${message}
      </p>
    `)
  } else {
    existingInlineError.innerText = message
  }

  window.scrollTo({ top: 0 }) // Scroll to top
  desktopSummary?.focus()
}

// Remove all error messages
const hideError = () => {
  document.querySelectorAll('.govuk-error-summary').forEach(el => el.remove())
  document.getElementById(currentLocationErrorId)?.remove()

  // Remove hide-mobile class from the H1 label wrapper
  const labelWrapper = document.querySelector('.govuk-label-wrapper')
  labelWrapper?.classList.remove('hide-mobile')

  const mobileHeading = document.querySelector('.govuk-label.map-mobile-only ')
  mobileHeading?.classList.remove('hide-error')
}

// Dismiss keyboard on mobile
const blurLocationInput = () => {
  document.getElementById('location').blur()
}

// Format autocomplete suggestion for display
const getLocationName = (value) => {
  let location = ''
  if (value?.GAZETTEER_ENTRY.NAME1) {
    location = value.GAZETTEER_ENTRY.NAME1
    if (value.GAZETTEER_ENTRY.COUNTY_UNITARY) {
      location += ` | ${value.GAZETTEER_ENTRY.COUNTY_UNITARY}`
    } else if (value.GAZETTEER_ENTRY.REGION) {
      location += ` | ${value.GAZETTEER_ENTRY.REGION}`
    } else {
      // do nothing
    }
  }
  return location
}

// Initialise autocomplete
const initialiseLocationSearch = () => {
  accessibleAutocomplete({
    element: document.querySelector('#location-container'),
    id: 'location',
    placeholder: 'Search for a place in England',
    minLength: 3,
    autoselect: false,
    showNoOptionsFound: true,
    displayMenu: 'overlay',

    templates: {
      suggestion: getLocationName, // Show suggestion text
      inputValue: v => v?.GAZETTEER_ENTRY.NAME1 // Value inserted into input
    },

    // Fetch autocomplete suggestions
    source: async (query, populateResults) => {
      autoCompleteValue = null // Reset selected value

      const response = await fetch(`/api/location-suggestions?location=${query}`)
      const data = await response.json()

      // Filter results to England only
      const englandMatches = data.filter(item =>
        item.GAZETTEER_ENTRY.COUNTRY === 'England' &&
        item.GAZETTEER_ENTRY.NAME1.toLowerCase().replaceAll(' ', '')
          .includes(query.toLowerCase().replaceAll(' ', ''))
      )

      populateResults(englandMatches)
    },

    // Handle selecting an autocomplete result
    onConfirm: (value) => {
      hideError() // Hide errors after selection
      if (value) {
        blurLocationInput() // Close mobile keyboard
        panToOSValue(value) // Pan map to selection
      } else {
        autoCompleteValue = value
      }
    }
  })

  // Create clearbutton next to input
  setTimeout(() => {
    const wrapper = document.querySelector('.location-input-wrapper')
    const input = document.getElementById('location')

    if (!wrapper || !input) {
      return
    }

    const clearBtn = document.createElement('button')
    clearBtn.type = 'button'
    clearBtn.className = 'clear-input-button'
    clearBtn.setAttribute('aria-label', 'Clear search input')

    clearBtn.innerHTML = `
      <svg aria-hidden="true" width="20" height="20" viewBox="0 0 20 20">
        <path d="M10,8.6L15.6,3L17,4.4L11.4,10L17,15.6L15.6,17L10,11.4L4.4,17L3,15.6L8.6,10L3,4.4L4.4,3L10,8.6Z"></path>
      </svg>
    `

    wrapper.appendChild(clearBtn)

    // Show/hide clear button based on input
    const toggleClear = () => {
      clearBtn.style.display = input.value ? 'block' : 'none'
    }

    input.addEventListener('input', toggleClear)

    // Clear input field on button click
    clearBtn.addEventListener('click', () => {
      input.value = ''
      input.dispatchEvent(new Event('input'))
      autoCompleteValue = null
      hideError()
      input.focus()
      toggleClear()
    })

    toggleClear() // Initial state
  }, 0)

  // Mobile: pressing Enter/Go triggers search button
  const locationTextBox = document.getElementById('location')
  locationTextBox.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') {
      e.preventDefault()
      hideError()
      locationSearchButton.click()
      blurLocationInput()
    }
  })
}

export {
  initialiseLocationSearch
}
