version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=foo
      - REDIS_PORT=6379
      - REDIS_ARGS=""
    networks:
      - default

  ##############################################################################################################
  # Redis commander on port 8081
  ##############################################################################################################
  redis_commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis
    deploy:
      restart_policy:
        condition: on-failure
  
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    command: "azurite --skipApiVersionCheck --blobHost 0.0.0.0 --queueHost 0.0.0.0"
    ports:
      - "10000:10000"
      - "10001:10001"

volumes:
  redisdata:
    driver: local


    