version: "3.9"
services:
  webapp:
    image: ${CONTAINER_REGISTRY:-webapp}/smart-incident-reporting:${TAG:-latest}
    build:
      context: ../
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379