import OdourJourney from '../actions/odour_actions.js'
import { odourDataset } from '../data/odour_dataset.js'
import SignInActions from '../actions/sign_in_actions.js'

const sleep = async (ms) => new Promise(resolve => setTimeout(resolve, ms))

describe('Odour E2E Tests @odour @regression', () => {
  before(async () => {
    await browser.url('/')
    await SignInActions.handleCookies()
  })
  it('Odour Journey - E2E Test-2', async () => {
    await browser.url('/')
    await OdourJourney.gotoOdourReport()
    await OdourJourney.startNow()
    await OdourJourney.verifySourcePage()
    await OdourJourney.selectSource(0)
    await OdourJourney.verifySourceDetailsPage(0)
    await OdourJourney.selectSourceDetails(0)
    await OdourJourney.verifyLocationHomePage()
    await OdourJourney.selectLocationHome(0)
    await OdourJourney.fillFindAddress()
    await OdourJourney.selectRadioButtonsOption('Ghyll Mount')
    await sleep(2000)
    await OdourJourney.confirmAddress()
    await sleep(2000)
    await OdourJourney.selectPreviousOption(0)
    await OdourJourney.verifyStartDateTimePage()
    await OdourJourney.selectStartDateTime(0)
    await OdourJourney.verifyIsSmellStillTherePage()
    await OdourJourney.selectIsSmellStillThere(0)
    await OdourJourney.verifySmellStrengthPage()
    await OdourJourney.selectSmellStrength(0)
    await OdourJourney.verifySmellNoticeableIndoorsPage()
    await OdourJourney.selectSmellNoticeableIndoors(0)
    await OdourJourney.verifySmellStickToClothsAndHairPage()
    await OdourJourney.selectSmellStickToClothsAndHair(0)
    await OdourJourney.verifyEffectOnDailyLifePage()
    await OdourJourney.selectEffectOnDailyLife(0)
    await OdourJourney.verifyEffectOnHealthPage()
    await OdourJourney.selectEffectOnHealth(0)
    await OdourJourney.verifyMedicalHelpPage()
    await OdourJourney.selectMedicalHelp(0)
    await OdourJourney.verifyContactPage()
    await OdourJourney.selectContact(0)
    await OdourJourney.verifyContactDetailsPage()
    await OdourJourney.fillContactDetailsPage()
    await OdourJourney.verifyImageOrVideoPage()
    await OdourJourney.selectImagesOrVideo(0)
    await OdourJourney.verifyOtherInformationPage()
    await sleep(2000)
    await OdourJourney.fillOtherInformation()
    await OdourJourney.verifyReportSent()
  })

  odourDataset.forEach(({ source, location, smellNoticeable }) => {
    it(`Odour Journey - E2E Test-2 should run with source=${source}, location=${location}, smellNoticeable=${smellNoticeable}`, async () => {
      await browser.url('/')
      await OdourJourney.gotoOdourReport()
      await OdourJourney.startNow()
      await OdourJourney.verifySourcePage()
      await OdourJourney.selectSource(source)
      await OdourJourney.selectSourceDetails(0)
      await OdourJourney.selectLocationHome(1)
      await OdourJourney.completeLocationOption(location)
      await sleep(2000)
      if (location === 1) {
        await OdourJourney.confirmAddress()
      }
      await OdourJourney.selectPreviousOption(0)
      await OdourJourney.verifyStartDateTimePage()
      await OdourJourney.selectStartDateTime(0)
      await OdourJourney.selectIsSmellStillThere(0)
      await OdourJourney.selectSmellStrength(0)
      await OdourJourney.selectSmellNoticeableIndoors(smellNoticeable)
      await OdourJourney.verifySmellStickToClothsAndHairPage(smellNoticeable)
      await OdourJourney.selectSmellStickToClothsAndHair(0)
      await OdourJourney.verifyEffectOnDailyLifePage()
      await OdourJourney.selectEffectOnDailyLife(0)
      await OdourJourney.verifyEffectOnHealthPage()
      await OdourJourney.selectEffectOnHealth(0)
      await OdourJourney.verifyMedicalHelpPage()
      await OdourJourney.selectMedicalHelp(0)
      await OdourJourney.selectContact(0)
      await OdourJourney.verifyContactDetailsPage()
      await sleep(2000)
      await OdourJourney.fillContactDetailsPage()
      await sleep(2000)
      await OdourJourney.verifyImageOrVideoPage()
      await sleep(2000)
      await OdourJourney.selectImagesOrVideo(0)
      await OdourJourney.verifyOtherInformationPage()
      await sleep(2000)
      await OdourJourney.fillOtherInformation()
      await OdourJourney.verifyReportSent()
    })
  })

  it('New Odour Journey - Report local council', async () => {
    await browser.url('/')
    await OdourJourney.gotoOdourReport()
    await OdourJourney.startNow()
    await sleep(2000)
    await OdourJourney.selectSource(4)
    await OdourJourney.verifyReportLocalCouncil()
  })

  it('New Odour Journey - Contact local council', async () => {
    await browser.url('/')
    await OdourJourney.gotoOdourReport()
    await OdourJourney.startNow()
    await sleep(2000)
    await OdourJourney.selectSource(7)
    await OdourJourney.verifyContactLocalCouncil()
  })

  it('New Odour Journey - No Source Details', async () => {
    await browser.url('/')
    await OdourJourney.gotoOdourReport()
    await OdourJourney.startNow()
    await sleep(2000)
    await OdourJourney.selectSource(3)
    await OdourJourney.selectSourceDetails(1)
    await OdourJourney.verifyContactLocalCouncil()
  })
})
