import WaterPollutionJourney from '../actions/water_pollution_actions.js'
import SignInActions from '../actions/sign_in_actions.js'

const sleep = async (ms) => new Promise(resolve => setTimeout(resolve, ms))

describe('Water Pollution E2E Tests @water_pollution @regression', () => {
  before(async () => {
    await browser.url('/')
    await SignInActions.handleCookies()
  })
  it('Water Pollution Journey - E2E Test', async () => {
    await browser.url('/')
    await sleep(2000)
    await WaterPollutionJourney.gotoWaterPollutionReport()
    await WaterPollutionJourney.startNow()
    await WaterPollutionJourney.verifySourcePage()
    await WaterPollutionJourney.selectSourceDetails(0)
    await WaterPollutionJourney.completeLocationOption(0)
    await WaterPollutionJourney.verifyStartDateTimePage()
    await WaterPollutionJourney.selectStartDateTime(0)
    await WaterPollutionJourney.verifyThinkPollutionIsPage()
    await WaterPollutionJourney.selectThinkPollutionIs(0)
    await WaterPollutionJourney.verifyTPollutionLooklikePage()
    await WaterPollutionJourney.selectPollutionLooklike(0)
    await WaterPollutionJourney.verifyPollutionComingFrom()
    await WaterPollutionJourney.selectPollutionComingFrom(1)
    await WaterPollutionJourney.verifyLessThan10Page()
    await WaterPollutionJourney.selectLessThan10Page(0)
    await WaterPollutionJourney.verifyDeadFishPage()
    await sleep(2000)
    await WaterPollutionJourney.selectDeadFishPage(0)
    await WaterPollutionJourney.verifyContactPage()
    await WaterPollutionJourney.selectContact(0)
    await WaterPollutionJourney.verifyContactDetailsPage()
    await WaterPollutionJourney.fillContactDetailsPage()
    await WaterPollutionJourney.verifyImageOrVideoPage()
    await WaterPollutionJourney.selectImagesOrVideo(0)
    await WaterPollutionJourney.verifyOtherInformationPage()
    await WaterPollutionJourney.fillOptionalInformation()
    await WaterPollutionJourney.verifyCheckYourAnswerPage()
    await WaterPollutionJourney.SendReport()
  })

  it('Water Pollution Journey Alternate Journey', async () => {
    await browser.url('/')
    await sleep(2000)
    await WaterPollutionJourney.gotoWaterPollutionReport()
    await WaterPollutionJourney.startNow()
    await WaterPollutionJourney.verifySourcePage()
    await WaterPollutionJourney.selectSourceDetails(5)
    await sleep(2000)
    await WaterPollutionJourney.completeLocationOption(1)
    await WaterPollutionJourney.verifyStartDateTimePage()
    await WaterPollutionJourney.selectStartDateTime(2)
    await WaterPollutionJourney.verifyThinkPollutionIsPage()
    await WaterPollutionJourney.selectThinkPollutionIs(4)
    await WaterPollutionJourney.verifyTPollutionLooklikePage()
    await WaterPollutionJourney.selectPollutionLooklike(2)
    await WaterPollutionJourney.verifyPollutionComingFrom()
    await WaterPollutionJourney.selectPollutionComingFrom(0)
    await WaterPollutionJourney.selectLessThan10Page(1)
    await sleep(2000)
    await WaterPollutionJourney.selectPollutionLength(0)
    await WaterPollutionJourney.verifyDeadFishPage()
    await WaterPollutionJourney.selectDeadFishPage(1)
    await WaterPollutionJourney.verifyContactPage()
    await WaterPollutionJourney.selectContact(0)
    await WaterPollutionJourney.fillContactDetailsPage()
    await WaterPollutionJourney.verifyImageOrVideoPage()
    await WaterPollutionJourney.selectImagesOrVideo(0)
    await WaterPollutionJourney.verifyOtherInformationPage()
    await WaterPollutionJourney.fillOptionalInformation()
    await WaterPollutionJourney.verifyCheckYourAnswerPage()
    await WaterPollutionJourney.SendReport()
  })
})
